### ISSUE TITLE
Not Bringnig Settings page

### ISSUE THREAD

**Issue by nwachira** [Focuslinkstech/phpnuxbill-captive-portal-plugin#1]
I installed the captive portal on my phpnuxbill all i see is the captive portal icon but when i click it takes me to the user side instead of the settings page

**Comment by Focuslinkstech** [comment]
Can you share screenshots as reference to this issue?

**Comment by nwachira** [comment]
![Screenshot from 2024-07-24 07-19-18](https://github.com/user-attachments/assets/f7beb8d4-d943-4c7b-a6c3-d911e53d4c11)
when I click on that captive portal it either just loads or takes me to the user page
![Screenshot from 2024-07-24 07-19-47](https://github.com/user-attachments/assets/c473112a-dbd4-4230-99b6-b6d2bb0575ca)
also how can i do away with that login part?

**Comment by Focuslinkstech** [comment]
Please check your server configuration, the plugin is working fine

**Comment by nwachira** [comment]
Problem is am not the only one with the issue so what am I missing?On Jul 24, 2024 10:57 AM, Focuslinkstech ***@***.***> wrote:
Please check your server configuration, the plugin is working fine

**Comment by Focuslinkstech** [comment]
![image](https://github.com/user-attachments/assets/308f51a2-0b85-4ff9-a740-c5d9f14988b4)

check your server configuration, am closing this issue

**Comment by nwachira** [comment]
Does it require json files? Since mine is missing json fileOn Jul 24, 2024 12:20 PM, Focuslinkstech ***@***.***> wrote:
Closed #1 as completed.

**Comment by Focuslinkstech** [comment]
>Does it require json files? Since mine is missing json file

nope the plugin will write the json files

**Comment by nwachira** [comment]
It wasn't a bug. It's permission issues. Super Admin isnt stated in the code so i had to create a user with just admin rights. Now am struggling to get packages on the user side.On Jul 24, 2024 4:27 PM, Focuslinkstech ***@***.***> wrote:

Does it require json files? Since mine is missing json file

nope the plugin will write the json files

**Comment by Focuslinkstech** [comment]
>Super Admin isnt stated in the code so i had to create a user with just admin rights.


I dont know where you get your own files  from anyway? 

![image](https://github.com/user-attachments/assets/be500c3a-4853-4800-82d2-97a61835e2a7)

**Comment by nwachira** [comment]
I got it from plugins page but I see now it was forked so they changed some parts. Let me use yours directly.On Jul 24, 2024 5:38 PM, Focuslinkstech ***@***.***> wrote:

Super Admin isnt stated in the code so i had to create a user with just admin rights.

I dont know where you get your own files  from anyway?
image.png (view on web)

**Comment by nwachira** [comment]
When is Pro version coming out and how much will it be?On Jul 24, 2024 5:44 PM, Unganisha Networks ***@***.***> wrote:I got it from plugins page but I see now it was forked so they changed some parts. Let me use yours directly.On Jul 24, 2024 5:38 PM, Focuslinkstech ***@***.***> wrote:

Super Admin isnt stated in the code so i had to create a user with just admin rights.

I dont know where you get your own files  from anyway?
image.png (view on web)

**Comment by Focuslinkstech** [comment]
>When is Pro version coming out and how much will it be?

its available already send me a message [@Focuslinkstech](https://t.me/focuslinkstech)
